### ISSUE TITLE
Trashcans 1.9-2.0.2 crashes dedicated Forge 1.10.2 build 2005 on startup

### ISSUE THREAD

**Issue by kreezxil** [gigabit101/Trashcans#6]
I got this from under the 1.10.2 tag you had available. But it comes back and complains that it only wants 1.9

```
Wrong Minecraft Versions!
Mod: Trashcans
Location: /root/binary-6-squared-mega-pack/mods/trashcans-1.10.2-1.9-2.0.2.jar
Expected: [1.9,1.9]
Current: Minecraft 1.10.2

```

Issue:  Trashcans 1.9-2.0.2 crashes dedicated Forge 1.10.2 build 2005 on startup

crash report:
https://gist.github.com/26f9939983454b95ca102b81680a6b7b

fml server latest:
https://gist.github.com/25e48fc492931219af0ea77335118878

**Comment by gigabit101** [comment]
will fix tomorrow simple fix

**Comment by 7934345** [comment]
wow~ 20 days ago, any update yet?

**Comment by gigabit101** [comment]
I forgot about this will push a build today my bad

**Comment by 7934345** [comment]
Please build for a new one. We ar waiting ;(

**Comment by Shadows-of-Fire** [comment]
Several months later...

**Comment by kreezxil** [comment]
There are some other mods that provide trashcans ...

**Comment by 7934345** [comment]
@kreezxil please tell me what mod has this feature? I search around and find nothing.

**Comment by kreezxil** [comment]
Look at the random collection mods. I'll get you the specifics later.

-----Original Message-----

**Comment by kreezxil** [comment]
To start there are pipes from [buildcraft ](https://minecraft.curseforge.com/projects/buildcraft?gameCategorySlug=mc-mods&projectID=61811) and [logistic pipes](https://minecraft.curseforge.com/projects/logistics-pipes?gameCategorySlug=mc-mods&projectID=232838) that can delete items and with a little ingenuity you can easy design a trash bin to surround them.

Here is a mod that uses specialized block type devices to get rid of stuff and is known as [Useful Nullifiers by Bartz24](https://minecraft.curseforge.com/projects/useful-nullifiers).

Actual Working Trashcans:
- [KalStuff](https://minecraft.curseforge.com/projects/kalstuff)
- [NeoTech](https://minecraft.curseforge.com/projects/neotech) - It's a trashbag, with a filter, when you pick up items matching the filter they go to oblivion.
- [Extra Utilities](https://mods.curse.com/mc-mods/minecraft/225561-extra-utilities) - Has three trashcans, one for items/blocks, one for energy, one for fluid
- [Storage Drawers](https://minecraft.curseforge.com/projects/storage-drawers) - has a void upgrade for its drawers, while technically not a trashcan, it will wipe excess inventory that overflows that drawer matching the drawers content.
- [Bagginses](https://minecraft.curseforge.com/projects/bagginses) - also not a trashcan, it has a void bag, that works like a trashcan.
- [Giacomo's Foundry](https://minecraft.curseforge.com/projects/giacomos-foundry) - also not a trashcan, but you can hook up inputs and outputs to it and then take all of your unwanted stuff and have it turned into new useable stuff.
- [Corail Recycler](https://minecraft.curseforge.com/projects/corail-recycler) - Similar to the Foundry above, it will recycle items.

And that's it, my research shows there is a need for trashcan/bin mods.

**Comment by 7934345** [comment]
really THX
have a nice day
